import boto3
import os
from app.config import REGION, AGENT_ID

# Create a Bedrock client
bedrock_client = boto3.client('bedrock', region_name=REGION)

def handle_general_query(user_query):
    """
    Handles general user queries by invoking a Bedrock Agent.

    Args:
        user_query (str): The user's natural language query.

    Returns:
        str: A natural language response generated by the Agent.
    """
    if not AGENT_ID:
        raise ValueError("Agent ID is not configured.")

    try:
        # Invoke the Bedrock Agent with the user query
        response = bedrock_client.invoke_agent(
            agentId=AGENT_ID,  # Use the Agent ID for Bedrock
            inputText=user_query,
            contentType="text/plain",
            accept="text/plain"
        )

        # Extract the response payload
        response_payload = response['body'].read().decode('utf-8')
        return response_payload.strip()

    except Exception as e:
        raise Exception(f"Failed to handle general query using Bedrock Agent: {str(e)}")
